local model=script.parent;
local Value=Instance.new("NumberValue");	--攻击
Value.Parent=model;
Value.Name="Attack";
Value.Value=40;
Value=Instance.new("NumberValue");	--防御
Value.Parent=model;
Value.Name="Defense";
Value.Value=20;
Value=Instance.new("NumberValue");	--血量
Value.Parent=model;
Value.Name="health";
Value.Value=100;
Value=Instance.new("StringValue");	--名字
Value.Parent=model;
Value.Name="name";
Value.Value="player";
Value=Instance.new("IntValue");		--行动力
Value.Parent=model;
Value.Name="mobility";
Value.Value=3;
Value=Instance.new("IntValue");		--占点数
Value.Parent=model;
Value.Name="partnumber";
Value.Value=0;
Value=Instance.new("StringValue");	--所在位置
Value.Parent=model;
Value.Name="currentPartID";
Value.Value="_55";
Value=Instance.new("IntValue");		--持有item的id
Value.Parent=model;
Value.Name="itemID";
Value.Value=0;