local model=script.parent;
local Value=Instance.new("NumberValue");	--攻击
Value.Parent=model;
Value.Name="Attack";
Value.Value=40;
Value=Instance.new("NumberValue");	--防御
Value.Parent=model;
Value.Name="Defense";
Value.Value=20;
Value=Instance.new("NumberValue");	--血量
Value.Parent=model;
Value.Name="health";
Value.Value=100;
Value=Instance.new("StringValue");	--名字
Value.Parent=model;
Value.Name="name";
Value.Value="player";
Value=Instance.new("IntValue");		--行动力
Value.Parent=model;
Value.Name="gameaction";
Value.Value=3;
Value=Instance.new("IntValue");		--x坐标
Value.Parent=model;
Value.Name="xla";
Value.Value=1;
Value=Instance.new("IntValue");		--y坐标
Value.Parent=model;
Value.Name="yla";
Value.Value=1;
Value=Instance.new("IntValue");		--总回合数
Value.Parent=model;
Value.Name="totalturn";
Value.Value=0;
Value=Instance.new("IntValue");		--是否在战斗中
Value.Parent=model;
Value.Name="infight";
Value.Value=0;
Value=Instance.new("IntValue");		--阵营
Value.Parent=model;
Value.Name="groupofpeople";
Value.Value=1;
Value=Instance.new("IntValue");		--占点数
Value.Parent=model;
Value.Name="partnumber";
Value.Value=0;
Value=Instance.new("StringValue");	--所在位置
Value.Parent=model;
Value.Name="nowplace";
Value.Value="011";
Value=Instance.new("IntValue");		--是否回合结束
Value.Parent=model;
Value.Name="outofturn";
Value.Value=0;
Value=Instance.new("IntValue");		--持有item的id
Value.Parent=model;
Value.Name="itemid";
Value.Value=0;